# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import common
from . import test_avatar_mixin
from . import test_ir_actions
from . import test_ir_actions_report
from . import test_ir_asset
from . import test_ir_attachment
from . import test_ir_config_parameter
from . import test_ir_cron
from . import test_ir_default
from . import test_ir_embedded_actions
from . import test_ir_filters
from . import test_ir_http
from . import test_ir_mail_server
from . import test_ir_mail_server_smtpd
from . import test_ir_model
from . import test_ir_module
from . import test_ir_qweb
from . import test_ir_qweb_fields
from . import test_ir_sequence
<<<<<<< e2b57350e198b4a15f00dce15c170cfdd4f81b00
from . import test_ir_ui_menu
from . import test_ir_ui_view
||||||| 20a8751588d670cd704cd2a7b76cd3eadedb8e90
from . import test_ir_sequence_date_range
from . import test_ir_embedded_actions
from . import test_ir_default
from . import test_lxml
from . import test_logging
from . import test_mail
from . import test_menu
from . import test_misc
from . import test_module
from . import test_module_graph
from . import test_orm
from . import test_ormcache
from . import test_overrides
from . import test_query
from . import test_qweb_field
from . import test_qweb
from . import test_res_config
from . import test_res_lang
from . import test_search
from . import test_split_table
from . import test_sql
from . import test_translate
from . import test_tz
# from . import test_uninstall  # loop
from . import test_user_has_group
from . import test_views
from . import test_res_company
from . import test_res_currency
from . import test_res_country
from . import test_res_partner
from . import test_res_partner_bank
from . import test_res_partner_merge
from . import test_res_users
from . import test_reports
from . import test_test_retry
from . import test_test_suite
from . import test_tests_tags
from . import test_transactions
from . import test_form_create
from . import test_cloc
from . import test_profiler
from . import test_pdf
from . import test_neutralize
from . import test_config_parameter
from . import test_ir_module_category
from . import test_configmanager
from . import test_num2words_ar
from . import test_cli
from . import test_signature
from . import test_import_files
=======
from . import test_ir_sequence_date_range
from . import test_ir_embedded_actions
from . import test_ir_default
from . import test_lxml
from . import test_logging
from . import test_mail
from . import test_menu
from . import test_misc
from . import test_module
from . import test_module_graph
from . import test_orm
from . import test_ormcache
from . import test_overrides
from . import test_query
from . import test_qweb_field
from . import test_qweb
from . import test_res_config
from . import test_res_lang
from . import test_search
from . import test_split_table
from . import test_sql
from . import test_translate
from . import test_tz
# from . import test_uninstall  # loop
from . import test_user_has_group
from . import test_views
from . import test_res_company
from . import test_res_currency
from . import test_res_country
from . import test_res_partner
from . import test_res_partner_bank
from . import test_res_partner_merge
from . import test_res_users
from . import test_reports
from . import test_test_retry
from . import test_test_suite
from . import test_tests_tags
from . import test_transactions
from . import test_form_create
from . import test_cloc
from . import test_profiler
from . import test_pdf
from . import test_neutralize
from . import test_config_parameter
from . import test_ir_module_category
from . import test_configmanager
from . import test_num2words_ar
from . import test_num2words_es
from . import test_cli
from . import test_signature
from . import test_import_files
>>>>>>> 2f85c23c9a4fc5f10a5a52ccb67230a58e70ff3d
from . import test_registry
from . import test_res_company
from . import test_res_config
from . import test_res_country
from . import test_res_currency
from . import test_res_groups
from . import test_res_groups_data
from . import test_res_lang
from . import test_res_partner
from . import test_res_partner_addresses
from . import test_res_partner_bank
from . import test_res_users
from . import test_res_users_has_group
from . import test_wizard_base_partner_merge
